### PR TITLE
Expose layoutAnimation config as props

### PR DESCRIPTION
**Pull request by sbycrosz**
So that we could customise them animations..

### CODE REVIEW

**Comment by Andr3wHur5t** [comment]
We will need to keep the current animation.

I can accept if you do something like `props.animationConfig || defaultAnimations` where `defaultAnimations` is the current `animations` object.

**Comment by sbycrosz** [comment]
done :+1:

**Comment by Andr3wHur5t** [comment]
Sorry, need to test this. Will do tonight.

**Comment by adrienbrault** [comment]
@Andr3wHur5t ping

**Comment by Andr3wHur5t** [comment]
Looks good 👍

**Pull request merged**
