### PR TITLE
Small changes for recent versions of React Native

### PR DESCRIPTION
**Pull request by abelgray**
This fixes a few warnings about things that will be changed in React 16.

### CODE REVIEW

**Comment by egorkhmelev** [comment]
Any chance its got merged soon? This one is pretty critical.

**Review by SteveMellross — APPROVED** [review]

**Comment by SteveMellross** [comment]
@Andr3wHur5t Please merge? 😁

**Comment by WillyRamirez** [comment]
@SteveMellross  do you know if @Andr3wHur5t  is still supporting this package?

**Comment by Andr3wHur5t** [comment]
This was fixed in another PR. I apologize for the latency on this; This got buried in my pile of notifications. 

Fix should on NPM momentarily.

**Pull request closed without merging**
